name = "SuperCowPowers"
uuid = "274d8e2e-b6eb-45cc-829c-fdd8ed05c44d"
authors = ["Akinori Machino"]
version = "0.1.0"

[deps]
TextWrap = "b718987f-49a8-5099-9789-dcd902bef87d"

[compat]
TextWrap = "1.0"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
