name = "SuperCowPowers"
uuid = "274d8e2e-b6eb-45cc-829c-fdd8ed05c44d"
authors = ["Akinori Machino <akinori.d.machino@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
